spring:
  application:
    name: account-service

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.blueyonder.bankingapp.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Added dialect

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: ${SERVER_PORT:7070}
