spring:
  application:
    name: notification-service

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  kafka:
    bootstrap-servers: ${KAFKA_SERVICE:localhost}:9092
    topic:
      notification: notification-topic
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.blueyonder.bankingapp.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE:localhost}:5432/capstone
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL_USERNAME}  # Use environment variables instead of hardcoding credentials
  password: ${EMAIL_PASSWORD}  # Secure this in environment variables or Vault
  protocol: smtp
  tls: true
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          trust: smtp.gmail.com

debug: true

logging:
  level:
    org.apache.kafka: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_SERVICE:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 9001
