spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false  # Disables auto-commit for better control

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"   # Allows access to all actuator endpoints
#  endpoint:
#    health:
#      show-details: always  # Provides full details in /actuator/health

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  # Change to true if you need service discovery
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 9001
